name: 功能建议
description: 为 O-Red 提出新功能
title: "[FEATURE] "
labels: ["enhancement", "needs triage"]
body:
  - type: markdown
    attributes:
      value: |
        感谢您为 O-Red 提出新功能建议！

        您的想法将帮助项目朝正确方向发展。

  - type: textarea
    id: summary
    attributes:
      label: 功能摘要
      description: 对请求功能的清晰简要描述
      placeholder: "我希望 O-Red 能..."
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: 要解决的问题
      description: 该功能将解决什么问题？
      placeholder: "我遇到了... / 有用的是..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: 建议的解决方案
      description: 详细描述希望看到的功能
      placeholder: "我建议添加..."
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: 受影响组件
      description: 哪个 O-Red 组件应包含此功能？
      options:
        - 中央 API (FastAPI)
        - Web 界面 (React)
        - 节点 P2P 客户端
        - O-RedMind (AI)
        - O-RedStore (Marketplace)
        - O-RedOffice (办公套件)
        - O-RedSearch (搜索引擎)
        - O-RedID (身份)
        - 文档
        - 基础设施
        - 新组件
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: 建议优先级
      description: 此功能有多重要？
      options:
        - 关键
        - 高
        - 中
        - 低
    validations:
      required: true

  - type: dropdown
    id: complexity
    attributes:
      label: 估计复杂度
      description: 你认为实现复杂度如何？
      options:
        - 简单
        - 中等
        - 复杂
        - 非常复杂
        - 我不知道

  - type: textarea
    id: alternatives
    attributes:
      label: 考虑的替代方案
      description: 你考虑过的其他方法
      placeholder: "我也考虑了..."

  - type: textarea
    id: implementation
    attributes:
      label: 实现建议
      description: 如果有实现想法，请分享
      placeholder: "这可以通过... 实现"

  - type: textarea
    id: mockups
    attributes:
      label: 原型或示例
      description: 如适用，请添加截图、原型或链接

  - type: dropdown
    id: contribution
    attributes:
      label: 你会参与实现吗？
      description: 你是否有兴趣参与实现此功能？
      options:
        - 是，我可以实现
        - 是，我可以提供指导
        - 我可以测试并提供反馈
        - 不，但我支持这个想法

  - type: textarea
    id: additional
    attributes:
      label: 额外上下文
      description: 可能有用的其他信息

  - type: checkboxes
    id: checklist
    attributes:
      label: 检查清单
      options:
        - label: 我确认没有提出过类似功能
          required: true
        - label: 此功能符合 O-Red 的理念
          required: true
        - label: 我提供了足够的细节
          required: true
